# ============================================
# RAKSHANA 24/7 — Alert Model
# ============================================
# Graduated alert system: 0-100 score
# Thresholds: >40 watch, >70 alert, >90 critical

import uuid
from datetime import datetime, timezone

from app import db


class Alert(db.Model):
    """Threat alert generated by the scanning pipeline."""

    __tablename__ = "alerts"

    id = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = db.Column(db.String(36), db.ForeignKey("users.id"), nullable=False, index=True)

    # Threat info
    threat_score = db.Column(db.Integer, nullable=False, default=0)  # 0-100
    threat_type = db.Column(db.String(50), nullable=False)  # stalking, morphed_image, doxxing, harassment, blackmail
    severity = db.Column(db.String(20), nullable=False)  # safe, watch, alert, critical

    # Source
    source_type = db.Column(db.String(30), nullable=False)  # telegram, paste_site, forum, image_search
    source_name = db.Column(db.String(255), nullable=True)  # e.g., "Telegram: @leaked_numbers"
    source_url = db.Column(db.Text, nullable=True)

    # Content
    title = db.Column(db.String(255), nullable=False)
    description = db.Column(db.Text, nullable=False)
    explanation = db.Column(db.Text, nullable=True)  # Plain-language explanation of why this is a threat
    matched_content = db.Column(db.Text, nullable=True)  # What was matched (redacted)

    # Legal reference
    applicable_laws = db.Column(db.Text, nullable=True)  # JSON: [{section, act, description}]

    # Action tracking
    is_read = db.Column(db.Boolean, default=False)
    is_dismissed = db.Column(db.Boolean, default=False)
    is_reported = db.Column(db.Boolean, default=False)
    action_taken = db.Column(db.String(50), nullable=True)  # screenshot, reported, contacted, dismissed

    # Notification status
    notification_sent = db.Column(db.Boolean, default=False)
    notification_type = db.Column(db.String(30), nullable=True)  # dashboard, email, sms, whatsapp
    trusted_contact_notified = db.Column(db.Boolean, default=False)

    # Timestamps
    detected_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))
    read_at = db.Column(db.DateTime, nullable=True)
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    def classify_severity(self):
        """Set severity based on threat score thresholds from PRD."""
        if self.threat_score >= 90:
            self.severity = "critical"
        elif self.threat_score >= 70:
            self.severity = "alert"
        elif self.threat_score >= 40:
            self.severity = "watch"
        else:
            self.severity = "safe"
        return self.severity

    def to_dict(self):
        import json

        return {
            "id": self.id,
            "user_id": self.user_id,
            "threat_score": self.threat_score,
            "threat_type": self.threat_type,
            "severity": self.severity,
            "source_type": self.source_type,
            "source_name": self.source_name,
            "source_url": self.source_url,
            "title": self.title,
            "description": self.description,
            "explanation": self.explanation,
            "matched_content": self.matched_content,
            "applicable_laws": json.loads(self.applicable_laws) if self.applicable_laws else [],
            "is_read": self.is_read,
            "is_dismissed": self.is_dismissed,
            "is_reported": self.is_reported,
            "action_taken": self.action_taken,
            "notification_sent": self.notification_sent,
            "notification_type": self.notification_type,
            "trusted_contact_notified": self.trusted_contact_notified,
            "detected_at": self.detected_at.isoformat() if self.detected_at else None,
            "read_at": self.read_at.isoformat() if self.read_at else None,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }

    def __repr__(self):
        return f"<Alert {self.id} score={self.threat_score} type={self.threat_type}>"
